/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package br.com.edu.dto;

import java.io.Serializable;
import java.util.*;

import br.com.edu.dao.*;
import br.com.edu.exceptions.*;
import br.com.edu.factory.*;

public class Automovel
{
	/** 
	 * This attribute maps to the column codigo in the automovel table.
	 */
	protected int codigo;

	/** 
	 * This attribute maps to the column marca in the automovel table.
	 */
	protected String marca;

	/** 
	 * This attribute maps to the column modelo in the automovel table.
	 */
	protected String modelo;

	/** 
	 * This attribute maps to the column cor in the automovel table.
	 */
	protected String cor;

	/** 
	 * This attribute maps to the column ano in the automovel table.
	 */
	protected int ano;

	/** 
	 * This attribute represents whether the primitive attribute ano is null.
	 */
	protected boolean anoNull = true;

	/** 
	 * This attribute maps to the column motor in the automovel table.
	 */
	protected float motor;

	/** 
	 * This attribute represents whether the primitive attribute motor is null.
	 */
	protected boolean motorNull = true;

	/** 
	 * This attribute maps to the column cod_tipo in the automovel table.
	 */
	protected int codTipo;

	/**
	 * Method 'Automovel'
	 * 
	 */
	public Automovel()
	{
	}

	/**
	 * Method 'getCodigo'
	 * 
	 * @return int
	 */
	public int getCodigo()
	{
		return codigo;
	}

	/**
	 * Method 'setCodigo'
	 * 
	 * @param codigo
	 */
	public void setCodigo(int codigo)
	{
		this.codigo = codigo;
	}

	/**
	 * Method 'getMarca'
	 * 
	 * @return String
	 */
	public String getMarca()
	{
		return marca;
	}

	/**
	 * Method 'setMarca'
	 * 
	 * @param marca
	 */
	public void setMarca(String marca)
	{
		this.marca = marca;
	}

	/**
	 * Method 'getModelo'
	 * 
	 * @return String
	 */
	public String getModelo()
	{
		return modelo;
	}

	/**
	 * Method 'setModelo'
	 * 
	 * @param modelo
	 */
	public void setModelo(String modelo)
	{
		this.modelo = modelo;
	}

	/**
	 * Method 'getCor'
	 * 
	 * @return String
	 */
	public String getCor()
	{
		return cor;
	}

	/**
	 * Method 'setCor'
	 * 
	 * @param cor
	 */
	public void setCor(String cor)
	{
		this.cor = cor;
	}

	/**
	 * Method 'getAno'
	 * 
	 * @return int
	 */
	public int getAno()
	{
		return ano;
	}

	/**
	 * Method 'setAno'
	 * 
	 * @param ano
	 */
	public void setAno(int ano)
	{
		this.ano = ano;
		this.anoNull = false;
	}

	/**
	 * Method 'setAnoNull'
	 * 
	 * @param value
	 */
	public void setAnoNull(boolean value)
	{
		this.anoNull = value;
	}

	/**
	 * Method 'isAnoNull'
	 * 
	 * @return boolean
	 */
	public boolean isAnoNull()
	{
		return anoNull;
	}

	/**
	 * Method 'getMotor'
	 * 
	 * @return float
	 */
	public float getMotor()
	{
		return motor;
	}

	/**
	 * Method 'setMotor'
	 * 
	 * @param motor
	 */
	public void setMotor(float motor)
	{
		this.motor = motor;
		this.motorNull = false;
	}

	/**
	 * Method 'setMotorNull'
	 * 
	 * @param value
	 */
	public void setMotorNull(boolean value)
	{
		this.motorNull = value;
	}

	/**
	 * Method 'isMotorNull'
	 * 
	 * @return boolean
	 */
	public boolean isMotorNull()
	{
		return motorNull;
	}

	/**
	 * Method 'getCodTipo'
	 * 
	 * @return int
	 */
	public int getCodTipo()
	{
		return codTipo;
	}

	/**
	 * Method 'setCodTipo'
	 * 
	 * @param codTipo
	 */
	public void setCodTipo(int codTipo)
	{
		this.codTipo = codTipo;
	}
	
	/**
	 * Method 'createPk'
	 * 
	 * @return AutomovelPk
	 */
	public AutomovelPk createPk()
	{
		return new AutomovelPk(codigo);
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Automovel)) {
			return false;
		}
		
		final Automovel _cast = (Automovel) _other;
		if (codigo != _cast.codigo) {
			return false;
		}
		
		if (marca == null ? _cast.marca != marca : !marca.equals( _cast.marca )) {
			return false;
		}
		
		if (modelo == null ? _cast.modelo != modelo : !modelo.equals( _cast.modelo )) {
			return false;
		}
		
		if (cor == null ? _cast.cor != cor : !cor.equals( _cast.cor )) {
			return false;
		}
		
		if (ano != _cast.ano) {
			return false;
		}
		
		if (anoNull != _cast.anoNull) {
			return false;
		}
		
		if (motor != _cast.motor) {
			return false;
		}
		
		if (motorNull != _cast.motorNull) {
			return false;
		}
		
		if (codTipo != _cast.codTipo) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "locadora.colevati.av2.dto.Automovel: " );
		ret.append( "codigo=" + codigo );
		ret.append( ", marca=" + marca );
		ret.append( ", modelo=" + modelo );
		ret.append( ", cor=" + cor );
		ret.append( ", ano=" + ano );
		ret.append( ", motor=" + motor );
		ret.append( ", codTipo=" + codTipo );
		return ret.toString();
	}

}
