/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package br.com.edu.dto;

import java.io.Serializable;
import java.util.*;

import br.com.edu.dao.*;
import br.com.edu.exceptions.*;
import br.com.edu.factory.*;

public class Cliente implements Serializable
{
	/** 
	 * This attribute maps to the column CPF in the cliente table.
	 */
	protected String cpf;

	/** 
	 * This attribute maps to the column CNH in the cliente table.
	 */
	protected String cnh;

	/** 
	 * This attribute represents whether the primitive attribute cnh is null.
	 */
	protected boolean cnhNull = true;

	/** 
	 * This attribute maps to the column nome in the cliente table.
	 */
	protected String nome;

	/** 
	 * This attribute maps to the column endereco in the cliente table.
	 */
	protected String endereco;

	/** 
	 * This attribute maps to the column telefone in the cliente table.
	 */
	protected int telefone;

	/** 
	 * This attribute represents whether the primitive attribute telefone is null.
	 */
	protected boolean telefoneNull = true;

	/** 
	 * This attribute maps to the column data_nascimento in the cliente table.
	 */
	protected String dataNascimento;

	/**
	 * Method 'Cliente'
	 * 
	 */
	public Cliente()
	{
	}

	/**
	 * Method 'getCpf'
	 * 
	 * @return int
	 */
	public String getCpf()
	{
		return cpf;
	}

	/**
	 * Method 'setCpf'
	 * 
	 * @param cpf
	 */
	public void setCpf(String cpf)
	{
		this.cpf = cpf;
	}

	/**
	 * Method 'getCnh'
	 * 
	 * @return int
	 */
	public String getCnh()
	{
		return cnh;
	}

	/**
	 * Method 'setCnh'
	 * 
	 * @param l
	 */
	public void setCnh(String l)
	{
		this.cnh = l;
		this.cnhNull = false;
	}

	/**
	 * Method 'setCnhNull'
	 * 
	 * @param value
	 */
	public void setCnhNull(boolean value)
	{
		this.cnhNull = value;
	}

	/**
	 * Method 'isCnhNull'
	 * 
	 * @return boolean
	 */
	public boolean isCnhNull()
	{
		return cnhNull;
	}

	/**
	 * Method 'getNome'
	 * 
	 * @return String
	 */
	public String getNome()
	{
		return nome;
	}

	/**
	 * Method 'setNome'
	 * 
	 * @param nome
	 */
	public void setNome(String nome)
	{
		this.nome = nome;
	}

	/**
	 * Method 'getEndereco'
	 * 
	 * @return String
	 */
	public String getEndereco()
	{
		return endereco;
	}

	/**
	 * Method 'setEndereco'
	 * 
	 * @param endereco
	 */
	public void setEndereco(String endereco)
	{
		this.endereco = endereco;
	}

	/**
	 * Method 'getTelefone'
	 * 
	 * @return int
	 */
	public int getTelefone()
	{
		return telefone;
	}

	/**
	 * Method 'setTelefone'
	 * 
	 * @param telefone
	 */
	public void setTelefone(int telefone)
	{
		this.telefone = telefone;
		this.telefoneNull = false;
	}

	/**
	 * Method 'setTelefoneNull'
	 * 
	 * @param value
	 */
	public void setTelefoneNull(boolean value)
	{
		this.telefoneNull = value;
	}

	/**
	 * Method 'isTelefoneNull'
	 * 
	 * @return boolean
	 */
	public boolean isTelefoneNull()
	{
		return telefoneNull;
	}

	/**
	 * Method 'getDataNascimento'
	 * 
	 * @return String
	 */
	public String getDataNascimento()
	{
		return dataNascimento;
	}

	/**
	 * Method 'setDataNascimento'
	 * 
	 * @param dataNascimento
	 */
	public void setDataNascimento(String dataNascimento)
	{
		this.dataNascimento = dataNascimento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Cliente)) {
			return false;
		}
		
		final Cliente _cast = (Cliente) _other;
		if (cpf != _cast.cpf) {
			return false;
		}
		
		if (cnh != _cast.cnh) {
			return false;
		}
		
		if (cnhNull != _cast.cnhNull) {
			return false;
		}
		
		if (nome == null ? _cast.nome != nome : !nome.equals( _cast.nome )) {
			return false;
		}
		
		if (endereco == null ? _cast.endereco != endereco : !endereco.equals( _cast.endereco )) {
			return false;
		}
		
		if (telefone != _cast.telefone) {
			return false;
		}
		
		if (telefoneNull != _cast.telefoneNull) {
			return false;
		}
		
		if (dataNascimento == null ? _cast.dataNascimento != dataNascimento : !dataNascimento.equals( _cast.dataNascimento )) {
			return false;
		}
		
		return true;
	}


	/**
	 * Method 'createPk'
	 * 
	 * @return ClientePk
	 */
	public ClientePk createPk()
	{
		return new ClientePk(cpf);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "locadora.colevati.av2.dto.Cliente: " );
		ret.append( "cpf=" + cpf );
		ret.append( ", cnh=" + cnh );
		ret.append( ", nome=" + nome );
		ret.append( ", endereco=" + endereco );
		ret.append( ", telefone=" + telefone );
		ret.append( ", dataNascimento=" + dataNascimento );
		return ret.toString();
	}

}
