/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package br.com.edu.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the tipo table.
 */
public class TipoPk implements Serializable
{
	protected int codigo;

	/** 
	 * This attribute represents whether the primitive attribute codigo is null.
	 */
	protected boolean codigoNull;

	/** 
	 * Sets the value of codigo
	 */
	public void setCodigo(int codigo)
	{
		this.codigo = codigo;
	}

	/** 
	 * Gets the value of codigo
	 */
	public int getCodigo()
	{
		return codigo;
	}

	/**
	 * Method 'TipoPk'
	 * 
	 */
	public TipoPk()
	{
	}

	/**
	 * Method 'TipoPk'
	 * 
	 * @param codigo
	 */
	public TipoPk(final int codigo)
	{
		this.codigo = codigo;
	}

	/** 
	 * Sets the value of codigoNull
	 */
	public void setCodigoNull(boolean codigoNull)
	{
		this.codigoNull = codigoNull;
	}

	/** 
	 * Gets the value of codigoNull
	 */
	public boolean isCodigoNull()
	{
		return codigoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TipoPk)) {
			return false;
		}
		
		final TipoPk _cast = (TipoPk) _other;
		if (codigo != _cast.codigo) {
			return false;
		}
		
		if (codigoNull != _cast.codigoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + codigo;
		_hashCode = 29 * _hashCode + (codigoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "locadora.colevati.av2.dto.TipoPk: " );
		ret.append( "codigo=" + codigo );
		return ret.toString();
	}

}
