/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package br.com.edu.factory;

import java.sql.Connection;

import br.com.edu.dao.*;
import br.com.edu.jdbc.*;

public class LocacaoDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return LocacaoDao
	 */
	public static LocacaoDao create()
	{
		return new LocacaoDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return LocacaoDao
	 */
	public static LocacaoDao create(Connection conn)
	{
		return new LocacaoDaoImpl( conn );
	}

}
