/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package br.com.edu.dao;

import java.sql.CallableStatement;

import br.com.edu.dto.*;
import br.com.edu.exceptions.*;

public interface AutomovelDao
{
	/** 
	 * Inserts a new row in the automovel table.
	 */
	public boolean insert(Automovel dto) throws AutomovelDaoException;

	/** 
	 * Updates a single row in the automovel table.
	 * @return 
	 */
	public boolean update(AutomovelPk pk, Automovel dto) throws AutomovelDaoException;

	/** 
	 * Deletes a single row in the automovel table.
	 * @return 
	 */
	public boolean delete(AutomovelPk pk) throws AutomovelDaoException;

	/** 
	 * Returns the rows from the automovel table that matches the specified primary-key value.
	 */
	public Automovel findByPrimaryKey(AutomovelPk pk) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria 'codigo = :codigo'.
	 */
	public Automovel findByPrimaryKey(int codigo) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria ''.
	 */
	public Automovel[] findAll() throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria 'cod_tipo = :codTipo'.
	 */
	public Automovel[] findByTipo(int codTipo) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria 'codigo = :codigo'.
	 */
	public Automovel[] findWhereCodigoEquals(int codigo) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria 'marca = :marca'.
	 */
	public Automovel[] findWhereMarcaEquals(String marca) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria 'modelo = :modelo'.
	 */
	public Automovel[] findWhereModeloEquals(String modelo) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria 'cor = :cor'.
	 */
	public Automovel[] findWhereCorEquals(String cor) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria 'ano = :ano'.
	 */
	public Automovel[] findWhereAnoEquals(int ano) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria 'motor = :motor'.
	 */
	public Automovel[] findWhereMotorEquals(float motor) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the criteria 'cod_tipo = :codTipo'.
	 */
	public Automovel[] findWhereCodTipoEquals(int codTipo) throws AutomovelDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the automovel table that match the specified arbitrary SQL statement
	 */
	public Automovel[] findByDynamicSelect(String sql, Object[] sqlParams) throws AutomovelDaoException;

	/** 
	 * Returns all rows from the automovel table that match the specified arbitrary SQL statement
	 */
	public Automovel[] findByDynamicWhere(String sql, Object[] sqlParams) throws AutomovelDaoException;

}
