/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package br.com.edu.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the cliente table.
 */
public class ClientePk implements Serializable
{
	protected String cpf;

	/** 
	 * This attribute represents whether the primitive attribute cpf is null.
	 */
	protected boolean cpfNull;

	/** 
	 * Sets the value of cpf
	 */
	public void setCpf(String cpf)
	{
		this.cpf = cpf;
	}

	/** 
	 * Gets the value of cpf
	 */
	public String getCpf()
	{
		return cpf;
	}

	/**
	 * Method 'ClientePk'
	 * 
	 */
	public ClientePk()
	{
	}

	/**
	 * Method 'ClientePk'
	 * 
	 * @param cpf
	 */
	public ClientePk(final String cpf)
	{
		this.cpf = cpf;
	}

	/** 
	 * Sets the value of cpfNull
	 */
	public void setCpfNull(boolean cpfNull)
	{
		this.cpfNull = cpfNull;
	}

	/** 
	 * Gets the value of cpfNull
	 */
	public boolean isCpfNull()
	{
		return cpfNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ClientePk)) {
			return false;
		}
		
		final ClientePk _cast = (ClientePk) _other;
		if (cpf != _cast.cpf) {
			return false;
		}
		
		if (cpfNull != _cast.cpfNull) {
			return false;
		}
		
		return true;
	}


	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "locadora.colevati.av2.dto.ClientePk: " );
		ret.append( "cpf=" + cpf );
		return ret.toString();
	}

}
