/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package br.com.edu.jdbc;

import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;
import java.sql.CallableStatement;

import br.com.edu.dao.*;
import br.com.edu.dto.*;
import br.com.edu.exceptions.*;
import br.com.edu.factory.*;

public class TipoDaoImpl extends AbstractDAO implements TipoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT codigo, tipo FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( codigo, tipo ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET codigo = ?, tipo = ? WHERE codigo = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE codigo = ?";

	/** 
	 * Index of column codigo
	 */
	protected static final int COLUMN_CODIGO = 1;

	/** 
	 * Index of column tipo
	 */
	protected static final int COLUMN_TIPO = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column codigo
	 */
	protected static final int PK_COLUMN_CODIGO = 1;

	/** 
	 * Inserts a new row in the tipo table.
	 */
	public TipoPk insert(Tipo dto) throws TipoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		CallableStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareCall( SQL_INSERT );
			stmt.setInt( COLUMN_CODIGO, dto.getCodigo() );
			stmt.setString( COLUMN_TIPO, dto.getTipo() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			stmt.execute();
			int rows = stmt.getUpdateCount();
			System.out.println( rows + " rows affected" );
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the tipo table.
	 */
	public void update(TipoPk pk, Tipo dto) throws TipoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getCodigo() );
			stmt.setString( index++, dto.getTipo() );
			stmt.setInt( 3, pk.getCodigo() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the tipo table.
	 */
	public void delete(TipoPk pk) throws TipoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getCodigo() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the tipo table that matches the specified primary-key value.
	 */
	public Tipo findByPrimaryKey(TipoPk pk) throws TipoDaoException
	{
		return findByPrimaryKey( pk.getCodigo() );
	}

	/** 
	 * Returns all rows from the tipo table that match the criteria 'codigo = :codigo'.
	 */
	public Tipo findByPrimaryKey(int codigo) throws TipoDaoException
	{
		Tipo ret[] = findByDynamicSelect( SQL_SELECT + " WHERE codigo = ?", new Object[] {  new Integer(codigo) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the tipo table that match the criteria ''.
	 */
	public Tipo[] findAll() throws TipoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY codigo", null );
	}

	/** 
	 * Returns all rows from the tipo table that match the criteria 'codigo = :codigo'.
	 */
	public Tipo[] findWhereCodigoEquals(int codigo) throws TipoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE codigo = ? ORDER BY codigo", new Object[] {  new Integer(codigo) } );
	}

	/** 
	 * Returns all rows from the tipo table that match the criteria 'tipo = :tipo'.
	 */
	public Tipo[] findWhereTipoEquals(String tipo) throws TipoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE tipo = ? ORDER BY tipo", new Object[] { tipo } );
	}

	/**
	 * Method 'TipoDaoImpl'
	 * 
	 */
	public TipoDaoImpl()
	{
	}

	/**
	 * Method 'TipoDaoImpl'
	 * 
	 * @param userConn
	 */
	public TipoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "aluguel..tipo";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Tipo fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Tipo dto = new Tipo();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Tipo[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Tipo dto = new Tipo();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Tipo ret[] = new Tipo[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Tipo dto, ResultSet rs) throws SQLException
	{
		dto.setCodigo( rs.getInt( COLUMN_CODIGO ) );
		dto.setTipo( rs.getString( COLUMN_TIPO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Tipo dto)
	{
	}

	/** 
	 * Returns all rows from the tipo table that match the specified arbitrary SQL statement
	 */
	public Tipo[] findByDynamicSelect(String sql, Object[] sqlParams) throws TipoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the tipo table that match the specified arbitrary SQL statement
	 */
	public Tipo[] findByDynamicWhere(String sql, Object[] sqlParams) throws TipoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
